### ISSUE TITLE
Resize line doesn't line up with table

### ISSUE THREAD

**Issue by jamwaffles** [dobtco/jquery-resizable-columns#1]
As can be seen in the below image, the resize "cursor" (seen when clicking and dragging) is offset. It looks like the plugin isn't factoring the padding width into it's position calculations. This is on Chrome 27, Windows 8.

![resizebug](https://f.cloud.github.com/assets/800791/592595/c54cbce6-ca1e-11e2-844f-ad506f2fe5eb.png)

**Comment by ajb** [comment]
thanks, i'll look into this!

**Comment by ajb** [comment]
I've got a new version coming out that completely does away with this line. (And blows the current version of the plugin out of the water ;)

Thanks though for taking the time to file this!

**Comment by jamwaffles** [comment]
No problem at all, looking forward to the new version!

**Comment by ajb** [comment]
Out now, if you have a sec, take a look and let me how it works!

**Comment by jamwaffles** [comment]
In one word: Smoooooth! Definitely going to have to find a use for this in my next project.
