### ISSUE TITLE
Cut thead text, or overflow it.

### ISSUE THREAD

**Issue by rusboard** [dobtco/jquery-resizable-columns#13]
When thead title are too big, for example "NinjaGaidenCount", but there is data like only 2 numbers "33", then I think better have option, that overflow thead text or cut it and count width by tdoby columns.

I hope you understand my idea :)

**Comment by rusboard** [comment]
First set table style
table-layout: fixed;

then set TD Style
word-wrap:break-word

Almost good solution for this :)

**Comment by ajb** [comment]
I almost understand. Do you want to take a stab and submit a PR?

**Comment by tcosentino** [comment]
I think I am having the same problem. Here is a SO post asking about it http://stackoverflow.com/questions/19858114/resizing-table-columns-with-text-overflow-ellipsis-making-text-overlap

I'd love to submit a pull request but not sure what is going on in this case.

(in other news I am putting together a pull request to support multiple tbody in one table)

**Comment by Craga89** [comment]
Closing since this is really up to the user to apply the correct ellipsis styling
