### ISSUE TITLE
Narrowing column past its limit widens next column

### ISSUE THREAD

**Issue by Dawsain** [dobtco/jquery-resizable-columns#29]
Reproducible with FF 20.0, Chrome 34.0 and probably other browsers.

Steps to repro:

On a live demo page http://dobtco.github.io/jquery-resizable-columns/ click and drag the border between '#' and 'First Name' column to the left. Continue to drag it even when it reaches minimal size. If you reach the left side of the screen and your mouse won't move, release the button, then click and drag the border once more.

Expected result: after reaching its minimal width the '#' column doesn't change its width, and so do other columns.

Actual result: after reaching its minimal width the '#' column doesn't change its width, but the border between 'First Name' and 'Last name' starts moving to the right.

Screenshot:
![three_stages_of_dragging](https://cloud.githubusercontent.com/assets/7585377/2977249/2e28293e-dba9-11e3-9748-f2cc2010d8f8.gif)

**Comment by Craga89** [comment]
By default there is no maximum or minimum percentage the column widths can go. As you can see here:

``` coffee
maxWidth: null # Maximum `percentage` width to allow for any column
minWidth: null # Minimum `percentage` width to allow for any column
```

What's happening in this case, is that the width is going into a minus numbers... which creates some odd behaviour! Try setting the `minWidth` option to 0 :)

**Comment by ajb** [comment]
I'm reopening this, as I can reproduce the error and @Craga89's solution doesn't seem to help.

As far as I'm concerned, this is just a known issue -- tables are pretty flimsy, and I remember struggling with this when I wrote the first version of this library.

If anyone has any ideas on how to fix this, please speak up :). Thanks @Feigwar for the excellent bug report and annotated images.

**Comment by Craga89** [comment]
Hmm strange, the minimum width should definitely fix this, as I'm using it production and it no longer exhibits this behaviour. Can someone setup a reduced test case for this?

**Comment by Dawsain** [comment]
I haven't done any in-depth looking, but from my point of view it probably has to do with incorrect calculation of difference between initial width and new width when user moves the mouse out of the table borders. Must be sign change or something of that kind.

**Comment by Dawsain** [comment]
Looked into this and so far the main troubles that I see lie in the constrainWidth() function. First of all, if you set minWidth to 0 and start dragging some column border to the left beyond the table borders, it's possible to get a 0% width for that column. The real problem, however, is that you can get a 100+% width for the next column. That explains the sudden expanding. I think when you're doing constrainWidth(), you need to take into account not just minWidth and maxWidth, but look whether you have the mouse pointer out of the table borders.

For those looking for emulation, I've been able to repro it by this setup: https://drive.google.com/file/d/0BwbUACBWgyaDRl9OQ0Z4TEtTQVk/edit?pli=1 (download & open Безымянный.html).
