### ISSUE TITLE
Feature Request: Additional Table Change Detection To Call "syncHandleWidths"

### ISSUE THREAD

**Issue by cdaringe** [dobtco/jquery-resizable-columns#33]
Hi again:
I periodically hide and show my cols.  I found then my handles are off sync.  Looking through the code is see you've setup an event resize.rc, which I can manually call to to reset my handles.  However, I would be interested in discussing some solutions for detecting th {display: xxx} changes.  Thx!

**Comment by Craga89** [comment]
For this to work you'd need to wrap any method jQuery could use to change the `display` attribute, which is quite a few. There's not much scope for this, since you can, like you said, easily trigger the event at will, which is a much better idea :)
