### ISSUE TITLE
jQuery 2.1??

### ISSUE THREAD

**Issue by ksorbo** [dobtco/jquery-resizable-columns#35]
Does this plugin support jQuery 2.1?

When I run it, I get
Uncaught TypeError: Cannot read property 'msie' of undefined

**Comment by ajb** [comment]
Guess not!

**Comment by caneruguz** [comment]
Why is the dependency to jQuery 2.1? Can't it support earlier versions like 1.11?

**Comment by ajb** [comment]
Probably just an oversight. Feel free to PR.
