### ISSUE TITLE
Multiple Row thead

### ISSUE THREAD

**Issue by samsamet** [dobtco/jquery-resizable-columns#36]
I have a table which has two rows in the head of the table. The first is for the name of the columns and the second is for searching which has a input in it. I tried to use the plugin but i't didn't resize properly. Is there a way to apply the plugin into just on row? Also will applying the plugin into just one row solves my problem?

**Comment by Craga89** [comment]
Try the latest version, it will only match the first `<tr>` rows `<th>` or `<td>` elements now. Also see #37

**Comment by Craga89** [comment]
see #38
