### ISSUE TITLE
Jsbin example

### ISSUE THREAD

**Issue by BenjaminHorn** [dobtco/jquery-resizable-columns#45]
I have tried to make a JsBin for this plugin, but it seems, the rc-container and the rc-handlers are misplaced. Is there a way to test it in a JsBin?
http://jsbin.com/cevuzipiha/1/edit

**Comment by ajb** [comment]
You need to add `rel=stylesheet` to your <link> tag.

**Comment by BenjaminHorn** [comment]
@ajb  thanks

**Comment by ajb** [comment]
No prob. Best of luck!

On Thu, Apr 16, 2015 at 12:07 PM, BenjaminHorn notifications@github.com
wrote:

> @ajb https://github.com/ajb thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dobtco/jquery-resizable-columns/issues/45#issuecomment-93773512
> .

## 

Adam Becker
(951) 9-BECKER
@AdamJacobBecker
