### ISSUE TITLE
Is the library compatible with Browserify?

### ISSUE THREAD

**Issue by mathew-kurian** [dobtco/jquery-resizable-columns#49]

**Comment by Craga89** [comment]
Yep, Babel wraps in a UMD wrapper so it should work a treat in browserify

**Comment by mathew-kurian** [comment]
Unfortunately it doesn't. Says `./class` could not be found.

**Comment by Craga89** [comment]
Hmm, does it work if you require the class  directly? Perhaps `package.json` should be pointing to that instead...

``` js
require('jquery-resizable-columns/src/class');
```
