### ISSUE TITLE
Exclude certain columns?

### ISSUE THREAD

**Issue by kylebolstad** [dobtco/jquery-resizable-columns#5]
Is there a way to exclude certain columns from being resizable?

**Comment by ajb** [comment]
Yep. just add a `data-noresize` attribute to the `<th>`. Example here: http://dobtco.github.io/jquery-resizable-columns/

Unfortunately, this only prevents dragging the `noresize`'d column, and if you resize the other columns, it's possible that column will get bigger/smaller as well. Play around with the demo and you can probably see what I mean, and maybe you'll have a solution in mind :)
