### ISSUE TITLE
Does not allow resizing of new columns  even after re-calling resizableColumns

### ISSUE THREAD

**Issue by douglasg14b** [dobtco/jquery-resizable-columns#56]
Noticed this, if you have a dynamic table of sorts you cannot resize new columns, even if you call .resizableColumns() again off the table.

Maybe making an option to destroy the current resizableColumns and create a new one?

**Comment by douglasg14b** [comment]
Browsed around the source and found that there is a key for "destroy".

You can call .resizableColumns('destroy')

**Comment by ikunyemingor** [comment]
Used as:
`if ($_table.data('resizableColumns')) {
                $_table.resizableColumns('destroy');
            }
            $_table.resizableColumns();`
