### ISSUE TITLE
No mobile support

### ISSUE THREAD

**Issue by DCarty** [dobtco/jquery-resizable-columns#6]
This is a great however it does not respond to touch events and therefore does not work on mobile devices such as the iPad.  Real important feature nowadays.

**Comment by ajb** [comment]
I'm not quite sure how to implement this on touch devices, especially since I have nothing good to test with. Is it enough to bind to `ondblclick`?

**Comment by DCarty** [comment]
Here are some pointers:

on('mousedown') becomes: on('mousedown touchstart'

Then you'll have an issue with e.pageX which needs to be e.originalEvent.touches[0].pageX if mobile device

Really speaking there is not much you have to change in your code to make it mobile compatible.  Try and have a look if I get chance, but pressing deadlines are keeping me up at the moment.

**Comment by Craga89** [comment]
Touch events are now supported in the latest versions :)
