### ISSUE TITLE
Warning in console while using with webpack

### ISSUE THREAD

**Issue by smadapathi** [dobtco/jquery-resizable-columns#64]
I am trying to use this library and getting below warning in console. I am using this  library in my file using 'require'. Please let me know how to use this without getting warning in console.

```
This seems to be a pre-built javascript file. Though this is possible, it's not recommended.
Try to require the original source to get better results. 
@ ./~/jquery-resizable-columns/dist/jquery.resizableColumns.js
```

**Comment by Craga89** [comment]
See here: https://webpack.github.io/docs/configuration.html#module-noparse

**Comment by smadapathi** [comment]
Thanks!
