### ISSUE TITLE
destroy and refresh

### ISSUE THREAD

**Issue by iamdenny** [dobtco/jquery-resizable-columns#8]
I think there is no destroy and refresh method.
Can you please provide them?

**Comment by ajb** [comment]
Not documented, but they're in there: https://github.com/dobtco/jquery-resizable-columns/blob/gh-pages/coffee/jquery.resizableColumns.coffee

refresh = syncHandleWidths

**Comment by cdaringe** [comment]
What's the expected syntax to access, say, destroy?  I couldn't access it after the fact without returning it.  Any objection to returning the instances?

```
   return $.fn.extend({
     resizableColumns: function() {
-      var args, option;
+      var rcObjs = [],
+          args, option;
       option = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
-      return this.each(function() {
+      this.each(function() {
         var $table, data;
         $table = $(this);
         data = $table.data('resizableColumns');
         if (!data) {
           $table.data('resizableColumns', (data = new ResizableColumns($table, option)));
+          rcObjs.push(data);
         }
         if (typeof option === 'string') {
           return data[option].apply(data, args);
         }
       });
+      return rcObjs;
     }
   });
```

**Comment by ajb** [comment]
Accessing the instance: `$('table').data('resizableColumns')`
Calling methods:  `$('table').resizableColumns('destroy')`

Would love a PR that gets this into the README.

**Comment by pratik2pris** [comment]
var _resizableColumns = $("table").data('resizableColumns');
    if (_resizableColumns) {
        _resizableColumns.syncHandleWidths();
    }
